In [1]:
import numpy as np
import pandas as pd

In [111]:
pkCovid = pd.read_csv("C:\\Users\\shariq\\OneDrive\\Data Analysis Git\\Pakistan Corona Analysis\\pakistan corona dataset\\PK COVID-19.csv",nrows=847)

In [112]:
pkCovid.head(10)

,Date,Cases,Deaths,Recovered,Travel_history,Province,City
0,2/26/2020,1,0,0,China,Islamabad Capital Territory,Islamabad
1,2/26/2020,2,0,0,Iran/Taftan,Sindh,Karachi
2,2/29/2020,1,0,0,China,Islamabad Capital Territory,Islamabad
3,2/29/2020,1,0,0,Iran/Taftan,Sindh,Karachi
4,3/2/2020,1,0,0,Iran/Taftan,Gilgit-Baltistan,Gilgit
5,3/6/2020,0,0,1,Unknown,Sindh,Karachi
6,3/7/2020,1,0,0,Iran/Taftan,Sindh,Karachi
7,3/9/2020,6,0,0,Syria,Sindh,Karachi
8,3/9/2020,3,0,0,UK,Sindh,Karachi
9,3/10/2020,1,0,0,Iran/Taftan,Sindh,Karachi

In [113]:
pkCovid.tail(10)

,Date,Cases,Deaths,Recovered,Travel_history,Province,City
837,4/19/2020,1,0,0,Local - Social Contact,Punjab,Sahewal
838,4/19/2020,23,0,0,Local - Social Contact,Punjab,Sialkot
839,4/19/2020,0,0,1,Local - Social Contact,Punjab,Hafizabad
840,4/19/2020,7,0,0,Local - Social Contact,Punjab,Nankana
841,4/19/2020,0,0,4,Local - Social Contact,Punjab,Bahawalpur
842,4/19/2020,76,0,0,Local - Social Contact,Punjab,Lodhran
843,4/19/2020,5,0,0,Local - Social Contact,Punjab,Khanewal
844,4/19/2020,5,0,0,Local - Social Contact,Punjab,Toba Tek Singh
845,4/19/2020,3,0,0,Local - Social Contact,Punjab,Sheikhupura
846,4/19/2020,1,0,0,Local - Social Contact,Punjab,Bhakhar

In [114]:
pkCovid.Travel_history.unique()

array(['China', 'Iran/Taftan', 'Unknown', 'Syria', 'UK',
       'Local - Social Contact', 'USA', 'KSA', 'Local - Covid Relative',
       'International Passenger', 'Dubai', 'Tableeghi Jamaat',
       'Tableegi Jamaat', 'Jail', 'India'], dtype=object)

In [77]:
pkCovid["Travel_history"] = pkCovid['Travel_history'].replace("[ ].*","",regex=True)

In [79]:
pkCovid["Travel_history"] = pkCovid['Travel_history'].replace("Unknown","Local",regex=True)

In [95]:
pkCovid["Travel_history"] = pkCovid['Travel_history'].replace(["Tableeghi",'Tableegi','Jail'],"Local",regex=True)

In [108]:
pkCovid.head()

,Date,Cases,Deaths,Recovered,Travel_history,Province,City
0,2/26/2020,1,0,0,China,Islamabad Capital Territory,Islamabad
1,2/26/2020,2,0,0,Iran/Taftan,Sindh,Karachi
2,2/29/2020,1,0,0,China,Islamabad Capital Territory,Islamabad
3,2/29/2020,1,0,0,Iran/Taftan,Sindh,Karachi
4,3/2/2020,1,0,0,Iran/Taftan,Gilgit-Baltistan,Gilgit

In [115]:
pkCovid.Travel_history.unique()

array(['China', 'Iran/Taftan', 'Unknown', 'Syria', 'UK',
       'Local - Social Contact', 'USA', 'KSA', 'Local - Covid Relative',
       'International Passenger', 'Dubai', 'Tableeghi Jamaat',
       'Tableegi Jamaat', 'Jail', 'India'], dtype=object)

In [116]:
pkCovid['Province'].unique()

array(['Islamabad Capital Territory', 'Sindh', 'Gilgit-Baltistan',
       'Baluchistan', 'Punjab', 'Khyber Pakhtunkhwa',
       'khyber Pakhtunkhwa', 'Azad Jummu Kashmir',
       'Federal Administration Tribal Area'], dtype=object)

In [132]:
pkCovid[pkCovid['Province'] == 'Khyber Pakhtunkhwa'].head()

,Date,Cases,Deaths,Recovered,Travel_history,Province,City
21,3/15/2020,15,0,0,Iran/Taftan,Khyber Pakhtunkhwa,Dera Ismail Khan
22,3/15/2020,1,1,0,Unknown,Khyber Pakhtunkhwa,Mardan
29,3/16/2020,1,0,0,Unknown,Khyber Pakhtunkhwa,Mardan
35,3/17/2020,1,0,0,UK,Khyber Pakhtunkhwa,Charsadda
43,3/18/2020,1,0,0,Local - Social Contact,Khyber Pakhtunkhwa,Buner

In [133]:
pkCovid['Province'] = pkCovid['Province'].replace('khyber Pakhtunkhwa','Khyber Pakhtunkhwa',regex=True)

In [134]:
pkCovid['Province'].unique()

array(['Islamabad Capital Territory', 'Sindh', 'Gilgit-Baltistan',
       'Baluchistan', 'Punjab', 'Khyber Pakhtunkhwa',
       'Azad Jummu Kashmir', 'Federal Administration Tribal Area'],
      dtype=object)

In [138]:
pkCovid['Date'].unique()

array(['2/26/2020', '2/29/2020', '3/2/2020', '3/6/2020', '3/7/2020',
       '3/9/2020', '3/10/2020', '3/11/2020', '3/12/2020', '3/13/2020',
       '3/15/2020', '3/16/2020', '3/17/2020', '3/18/2020', '3/19/2020',
       '3/20/2020', '3/21/2020', '3/22/2020', '3/23/2020', '3/24/2020',
       '3/25/2020', '3/26/2020', '3/27/2020', '3/28/2020', '3/29/2020',
       '3/30/2020', '3/31/2020', '4/1/2020', '4/2/2020', '4/3/2020',
       '4/4/2020', '4/5/2020', '4/6/2020', '4/7/2020', '4/8/2020',
       '4/9/2020', '4/10/2020', '4/11/2020', '4/12/2020', '4/13/2020',
       '4/14/2020', '4/15/2020', '4/16/2020', '4/17/2020', '4/18/2020',
       '4/19/2020'], dtype=object)

In [59]:
pkCovid.isna().sum()

Date                0
Cases               0
Deaths              0
Recovered           0
Travel_history    847
Province            0
City                0
dtype: int64

In [34]:
pkCovid[['Deaths','Recovered','Province']].groupby(['Province']).mean()

                                      Deaths  Recovered
Province
Azad Jummu Kashmir                  0.000000   0.055556
Baluchistan                         0.138889   4.638889
Federal Administration Tribal Area  0.000000   0.343750
Gilgit-Baltistan                    0.051724   3.362069
Islamabad Capital Territory         0.068966   0.517241
Khyber Pakhtunkhwa                  0.240157   0.771654
Punjab                              0.137584   2.298658
Sindh                               0.466667   7.208333
khyber Pakhtunkhwa                  0.000000   0.000000

In [35]:
pkCovid[['Deaths','Recovered',"City",'Province']].groupby(['Province','City']).mean()

                                                          Deaths  Recovered
Province                           City
Azad Jummu Kashmir                 Bhambore             0.000000   0.000000
                                   Mirpur               0.000000   0.000000
                                   Muzaffarabad         0.000000   0.076923
                                   Trarkhel             0.000000   0.000000
Baluchistan                        Quetta               0.147059   4.911765
                                   Taftan               0.000000   0.000000
Federal Administration Tribal Area Bajaur               0.000000   0.714286
                                   Khyber               0.000000   0.125000
                                   Kurrum               0.000000   0.250000
                                   Mohmand              0.000000   0.000000
                                   North Waziristan     0.000000   0.500000
                                   South Waziristan     0.000000   0.250000
Gilgit-Baltistan                   Astore               0.200000   0.400000
                                   Diamer               0.000000   0.000000
                                   Ghanche              0.000000   1.666667
                                   Gilgit               0.000000   2.428571
                                   Kharmang             0.000000   1.250000
                                   Nagar                0.071429   4.285714
                                   Shigar               0.000000   3.800000
                                   Skardu               0.125000   8.125000
Islamabad Capital Territory        Islamabad            0.068966   0.517241
Khyber Pakhtunkhwa                 Abbottabad           0.142857   0.642857
                                   Bannu                0.100000   0.300000
                                   Buner                0.066667   0.466667
                                   Charsadda            0.000000   0.400000
                                   Dera Ismail Khan     0.111111   3.555556
                                   Dir Lower            0.181818   0.727273
                                   Dir Upper            0.000000   0.687500
                                   Hangu                0.000000   0.166667
                                   Hangu                1.000000   0.000000
...                                                          ...        ...
Punjab                             Raiwind              0.083333   0.083333
                                   Rajanpur             0.000000   0.000000
                                   Rawalpindi           0.052632   0.000000
                                   Sahewal              0.000000   0.000000
                                   Sargodha             0.000000   0.500000
                                   Sheikhupura          0.000000   0.000000
                                   Sialkot              0.000000   0.000000
                                   Toba Tek Singh       0.000000   0.000000
                                   Vehari               0.000000   0.857143
Sindh                              Badin                0.000000   0.000000
                                   Dadu                 0.000000   0.000000
                                   Ghotki               0.000000   0.000000
                                   Hyderabad            0.250000   9.000000
                                   Jacobabad            0.000000   0.000000
                                   Jamshoro             0.000000   0.000000
                                   Karachi              1.083333   4.395833
                                   Khairpur             0.000000   0.000000
                                   Larkana              0.000000   0.400000
                                   Naushero Feroz       0.000000   0.000000
                                   Sanghar              0.000000   0.000000
                                   Shaheed Benazirabad  0.000000   0.000000
                                   Shikarpur            0.000000   0.000000
                                   Shujawal             0.000000   0.000000
                                   Sujawal              0.000000   0.000000
                                   Sukkur               0.052632  28.631579
                                   Tando Alahyar        0.000000   0.000000
                                   Tando M. Khan        0.000000   0.000000
                                   Umerkot              0.000000   0.000000
khyber Pakhtunkhwa                 Mansehra             0.000000   0.000000
                                   Peshawar             0.000000   0.000000

[108 rows x 2 columns]

In [37]:
a = 'C:\\Users\shariq\OneDrive\Data Analysis Git\Pakistan Corona Analysis\pakistan corona dataset'

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-37-f0d1e9cd19fe>, line 1)

In [144]:
pkCovid[['Deaths',"City",'Province','Date','Cases','Recovered']].groupby(['Province','City','Date']).mean()

                                                  Deaths  Cases  Recovered
Province           City                Date
Azad Jummu Kashmir Bhambore            4/1/2020      0.0    2.0        0.0
                   Mirpur              3/18/2020     0.0    1.0        0.0
                                       3/26/2020     0.0    1.0        0.0
                                       4/5/2020      0.0    2.0        0.0
                   Muzaffarabad        3/29/2020     0.0    4.0        0.0
                                       4/10/2020     0.0    0.0        0.0
                                       4/11/2020     0.0    1.0        0.0
                                       4/12/2020     0.0    6.0        1.0
                                       4/13/2020     0.0    3.0        0.0
                                       4/15/2020     0.0    3.0        0.0
                                       4/17/2020     0.0    2.0        0.0
                                       4/19/2020     0.0    1.0        0.0
                                       4/4/2020      0.0    3.0        0.0
                                       4/6/2020      0.0    1.0        0.0
                                       4/7/2020      0.0    3.0        0.0
                                       4/8/2020      0.0   10.0        0.0
                                       4/9/2020      0.0    5.0        0.0
                   Trarkhel            4/1/2020      0.0    1.0        0.0
Baluchistan        Quetta              3/10/2020     0.0    1.0        0.0
                                       3/17/2020     0.0    2.0        0.0
                                       3/19/2020     0.0   53.0        0.0
                                       3/20/2020     0.0    5.0        0.0
                                       3/21/2020     0.0   12.0        0.0
                                       3/22/2020     1.0    4.0        0.0
                                       3/24/2020     0.0    2.0        0.0
                                       3/25/2020     0.0   10.5        0.0
                                       3/26/2020     0.0   12.0        0.0
                                       3/27/2020     0.0    0.0        2.0
                                       3/28/2020     0.0    5.0        0.0
                                       3/30/2020     0.0    6.0        0.0
...                                                  ...    ...        ...
Sindh              Shaheed Benazirabad 4/16/2020     0.0   53.0        0.0
                                       4/8/2020      0.0    7.0        0.0
                   Shikarpur           4/16/2020     0.0    3.0        0.0
                   Shujawal            4/8/2020      0.0    1.0        0.0
                   Sujawal             4/13/2020     0.0    1.0        0.0
                                       4/16/2020     0.0    5.0        0.0
                                       4/17/2020     0.0    2.0        0.0
                   Sukkur              3/15/2020     0.0   13.0        0.0
                                       3/16/2020     0.0  119.0        0.0
                                       3/17/2020     0.0   24.0        0.0
                                       3/18/2020     0.0   31.0        0.0
                                       3/21/2020     0.0   39.0        0.0
                                       3/22/2020     0.0   23.0        0.0
                                       3/23/2020     0.0   11.0        0.0
                                       3/24/2020     0.0    8.0        0.0
                                       3/30/2020     0.0    6.0       23.0
                                       3/31/2020     0.0    0.0       10.0
                                       4/14/2020     0.0    0.0        1.0
                                       4/15/2020     1.0    0.0        0.0
                                       4/16/2020     0.0   52.0        0.0
                                       4/18/2020     0.0    0.0      273.0
                                       4/2/2020      0.0    0.0        2.0
                                       4/6/2020      0.0    0.0      130.0
                                       4/8/2020      0.0    0.0       18.0
                                       4/9/2020      0.0    0.0       43.5
                   Tando Alahyar       4/16/2020     0.0    4.0        0.0
                   Tando M. Khan       4/16/2020     0.0    1.0        0.0
                                       4/17/2020     0.0    6.0        0.0
                                       4/8/2020      0.0   12.0        0.0
                   Umerkot             4/17/2020     0.0    1.0        0.0

[813 rows x 3 columns]

In [150]:
pd.options.display.max_columns
pkCovid['Date'].unique()

array(['2/26/2020', '2/29/2020', '3/2/2020', '3/6/2020', '3/7/2020',
       '3/9/2020', '3/10/2020', '3/11/2020', '3/12/2020', '3/13/2020',
       '3/15/2020', '3/16/2020', '3/17/2020', '3/18/2020', '3/19/2020',
       '3/20/2020', '3/21/2020', '3/22/2020', '3/23/2020', '3/24/2020',
       '3/25/2020', '3/26/2020', '3/27/2020', '3/28/2020', '3/29/2020',
       '3/30/2020', '3/31/2020', '4/1/2020', '4/2/2020', '4/3/2020',
       '4/4/2020', '4/5/2020', '4/6/2020', '4/7/2020', '4/8/2020',
       '4/9/2020', '4/10/2020', '4/11/2020', '4/12/2020', '4/13/2020',
       '4/14/2020', '4/15/2020', '4/16/2020', '4/17/2020', '4/18/2020',
       '4/19/2020'], dtype=object)

In [146]:
pkCovid['Date'].min()

'2/26/2020'

In [147]:
pkCovid['Date'].max()

'4/9/2020'